title: Haibin Yin's Homepage
page-top-title: Haibin Yin
top-section-bg-text: Data Science-Statistics
home-subtitle: Haibin Yin &ensp;|&ensp;尹海镔
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
